@extends('layouts.bento')
@section('title','Configuração Fiscal')
@section('page-title','Portal Contábil')
@section('page-subtitle',$tenant->name)
@php($bentoNavigation=\App\Support\PortalNavigation::make('accounting','settings',$tenant->slug))
@push('styles')<link rel="stylesheet" href="{{ asset('assets/accounting-portal.css') }}">@endpush
@section('content')
<main class="acc-shell"><header class="acc-topbar"><div class="acc-heading"><p class="acc-eyebrow">Configuração fiscal</p><h1>Preparação para emissão</h1><p>Defina o documento e a origem explícita do valor esperado.</p></div><a class="acc-button" href="{{ route('accounting.fiscal.index',['tenant'=>$tenant->slug]) }}">Voltar à fila</a></header>
 @if(session('success'))<div class="acc-panel"><div class="acc-action-box" style="color:var(--acc-success)">{{ session('success') }}</div></div>@endif
 <section class="acc-panel"><form class="acc-settings-form" method="GET"><label class="acc-field"><span>Escopo</span><select class="acc-select" name="project" onchange="this.form.submit()"><option value="">Padrão do tenant</option>@foreach($projects as $item)<option value="{{ $item->id }}" @selected($project?->id===$item->id)>{{ $item->title }}</option>@endforeach</select></label></form></section>
 <form method="POST" action="{{ route('accounting.fiscal.settings.store',['tenant'=>$tenant->slug]) }}" class="acc-panel">@csrf<input type="hidden" name="project_id" value="{{ $project?->id }}">
 <header class="acc-panel-head"><div><h2>{{ $project ? 'Override do projeto' : 'Configuração padrão' }}</h2><p>{{ $profile ? 'Versão '.$profile->version.' · '.($profile->status==='active'?'Ativa':'Rascunho') : 'Configuração pendente' }}</p></div></header>
 <div class="acc-settings-grid"><label class="acc-field"><span>Documento esperado</span><select class="acc-select" name="document_type"><option value="">Selecione</option>@foreach($documentTypes as $type)<option value="{{ $type->value }}" @selected(old('document_type',$profile?->document_type?->value)===$type->value)>{{ $type->label() }}</option>@endforeach</select></label>
 <label class="acc-field"><span>Regra do valor fiscal</span><select class="acc-select" name="amount_source"><option value="">Selecione</option>@foreach($amountSources as $source)<option value="{{ $source->value }}" @selected(old('amount_source',$profile?->amount_source?->value)===$source->value)>{{ $source->label() }}</option>@endforeach</select></label>
 <label class="acc-check"><input type="checkbox" name="require_issuer_tax_id" value="1" @checked(old('require_issuer_tax_id',$profile?->require_issuer_tax_id??true))> Exigir CNPJ do emitente</label><label class="acc-check"><input type="checkbox" name="require_issuer_address" value="1" @checked(old('require_issuer_address',$profile?->require_issuer_address??true))> Exigir endereço do emitente</label><label class="acc-check"><input type="checkbox" name="require_recipient_tax_id" value="1" @checked(old('require_recipient_tax_id',$profile?->require_recipient_tax_id??true))> Exigir documento do destinatário</label><label class="acc-check"><input type="checkbox" name="require_xml" value="1" @checked(old('require_xml',$profile?->require_xml??true))> Exigir XML futuramente</label><label class="acc-check"><input type="checkbox" name="require_pdf" value="1" @checked(old('require_pdf',$profile?->require_pdf??true))> Exigir PDF futuramente</label>
 <label class="acc-field acc-span"><span>Observação padrão</span><textarea class="acc-input" name="standard_notes" rows="4" maxlength="2000">{{ old('standard_notes',$profile?->standard_notes) }}</textarea></label><label class="acc-check acc-span"><input type="checkbox" name="active" value="1" @checked(old('active',$profile?->status==='active'))> Ativar esta versão</label></div>
 <div class="acc-action-box"><p class="acc-muted">Perfis incompletos podem ser salvos como rascunho. O Gate continuará bloqueando até a ativação e o preenchimento.</p>@can('manage_accounting_fiscal_settings')<button class="acc-button acc-button-primary" type="submit">Salvar nova versão</button>@endcan</div></form>
</main>@endsection
