@extends('layouts.bento')
@section('title','Resumo para Emissão')
@section('page-title','Portal Contábil')
@section('page-subtitle',$tenant->name)
@php($bentoNavigation=\App\Support\PortalNavigation::make('accounting','fiscal',$tenant->slug))
@push('styles')<link rel="stylesheet" href="{{ asset('assets/accounting-portal.css') }}">@endpush
@section('content')
<main class="acc-shell" data-fiscal-preparation><header class="acc-topbar"><div class="acc-heading"><p class="acc-eyebrow">Resumo auxiliar para emissão externa</p><h1>{{ $receipt->formatted_number }}</h1><p>Consulta de apoio para copiar dados durante a emissão. O documento oficial deste fluxo é o faturamento completo em PDF.</p></div><div class="acc-inline-actions"><a class="acc-button" href="{{ route('accounting.processes.show',['tenant'=>$tenant->slug,'receipt'=>$receipt]) }}"><i data-lucide="arrow-left"></i> Faturamento</a><a class="acc-button acc-button-primary" href="{{ route('accounting.fiscal.billing-sheet',['tenant'=>$tenant->slug,'receipt'=>$receipt]) }}" target="_blank" rel="noopener"><i data-lucide="printer"></i> Abrir faturamento completo</a></div></header>
 @if(session('success'))<div class="acc-alert">{{ session('success') }}</div>@endif
 <section class="acc-panel"><div class="acc-state-strip"><div class="acc-state-item"><span>Projeto</span><strong>{{ data_get($snapshot,'identity.project.name') }}</strong></div><div class="acc-state-item"><span>Autorização</span><strong>{{ $gate['authorization'] ? 'Rodada '.$gate['authorization']->sequence : 'Envio não exigido' }}</strong></div><div class="acc-state-item"><span>Documento</span><strong>{{ $gate['document_type_label'] }}</strong></div><div class="acc-state-item"><span>Valor fiscal esperado</span><strong>R$ {{ number_format((float)$gate['expected_fiscal_amount'],2,',','.') }}</strong></div></div>
 <div class="acc-tab-panel is-active"><div class="acc-detail-grid"><div class="acc-detail"><span>Emitente</span><strong>{{ $tenant->legal_name ?: $tenant->name }}</strong><button class="acc-copy" data-copy="{{ $tenant->legal_name ?: $tenant->name }} | CNPJ: {{ $tenant->cnpj }} | {{ $tenant->full_address }}">Copiar</button></div><div class="acc-detail"><span>Destinatário</span><strong>{{ data_get($snapshot,'recipient.name') }}</strong><button class="acc-copy" data-copy="{{ data_get($snapshot,'recipient.name') }} | Documento: {{ data_get($snapshot,'recipient.document') }} | {{ data_get($snapshot,'recipient.address') }}">Copiar</button></div><div class="acc-detail"><span>Período</span><strong>{{ data_get($snapshot,'identity.period.from') }} a {{ data_get($snapshot,'identity.period.to') }}</strong></div></div></div>
 <div class="acc-table-wrap" style="display:block"><table class="acc-table"><thead><tr><th>Produto</th><th>Quantidade</th><th>Unidade</th><th>Preço</th><th>Total</th></tr></thead><tbody>@foreach(data_get($snapshot,'lines',[]) as $line)<tr><td>{{ data_get($line,'product.name') }}</td><td>{{ number_format((float)data_get($line,'quantity'),3,',','.') }}</td><td>{{ data_get($line,'product.unit') }}</td><td>R$ {{ number_format((float)data_get($line,'unit_price'),2,',','.') }}</td><td>R$ {{ number_format((float)data_get($line,'gross'),2,',','.') }}</td></tr>@endforeach</tbody></table></div>
 <div class="acc-action-box"><div class="acc-detail-grid"><div class="acc-detail"><span>Valor bruto do faturamento</span><strong>R$ {{ number_format((float)data_get($snapshot,'totals.gross'),2,',','.') }}</strong></div><div class="acc-detail"><span>Ajustes</span><strong>R$ {{ number_format((float)data_get($snapshot,'totals.fees'),2,',','.') }}</strong></div><div class="acc-detail"><span>Valor indicado para emissão</span><strong>R$ {{ number_format((float)$gate['expected_fiscal_amount'],2,',','.') }}</strong></div></div>@if($gate['profile']->standard_notes)<div class="acc-detail"><span>Instruções para emissão</span><strong>{{ $gate['profile']->standard_notes }}</strong><button class="acc-copy" data-copy="{{ $gate['profile']->standard_notes }}">Copiar</button></div>@endif</div></section>
 <section class="acc-panel acc-print-control"><header class="acc-panel-head"><div><h2>Controle de emissão e conferência</h2><p>Preenchimento após a emissão no sistema externo.</p></div></header><div class="acc-settings-grid"><div class="acc-detail"><span>Número da nota/documento emitido</span><strong>________________________________</strong></div><div class="acc-detail"><span>Data da emissão</span><strong>____/____/________</strong></div><div class="acc-detail"><span>Responsável pela emissão</span><strong>________________________________</strong></div><div class="acc-detail"><span>Conferência</span><strong>☐ Dados conferidos &nbsp; ☐ Correção necessária</strong></div><div class="acc-detail acc-span"><span>Arquivos recebidos</span><strong>☐ PDF &nbsp; ☐ XML &nbsp; ☐ Outro comprovante</strong></div><div class="acc-detail acc-span"><span>Observações</span><strong>________________________________________________________________________________</strong></div></div></section>
</main>@endsection
@push('scripts')<script>document.addEventListener('click',async e=>{const b=e.target.closest('[data-copy]');if(!b)return;try{await navigator.clipboard.writeText(b.dataset.copy);b.textContent='Copiado';setTimeout(()=>b.textContent='Copiar',1200)}catch{const t=document.createElement('textarea');t.value=b.dataset.copy;document.body.append(t);t.select();document.execCommand('copy');t.remove();b.textContent='Copiado'}})</script>@endpush
