@extends('layouts.bento')
@section('title','Resumo para Emissão')
@section('page-title','Portal Contábil')
@section('page-subtitle',$tenant->name)
@php($bentoNavigation=\App\Support\PortalNavigation::make('accounting','fiscal',$tenant->slug))
@push('styles')<link rel="stylesheet" href="{{ asset('assets/accounting-portal.css') }}">@endpush
@section('content')
<main class="acc-shell" data-fiscal-preparation><header class="acc-topbar"><div class="acc-heading"><p class="acc-eyebrow">Resumo para emissão</p><h1>{{ $receipt->formatted_number }}</h1><p>Documento de apoio. Não é nota fiscal.</p></div><button class="acc-button" type="button" onclick="window.print()"><i data-lucide="printer"></i> Imprimir</button></header>
 <section class="acc-panel"><div class="acc-state-strip"><div class="acc-state-item"><span>Projeto</span><strong>{{ data_get($snapshot,'identity.project.name') }}</strong></div><div class="acc-state-item"><span>Autorização</span><strong>Rodada {{ $gate['authorization']->sequence }}</strong></div><div class="acc-state-item"><span>Documento</span><strong>{{ $gate['document_type_label'] }}</strong></div><div class="acc-state-item"><span>Valor fiscal esperado</span><strong>R$ {{ number_format((float)$gate['expected_fiscal_amount'],2,',','.') }}</strong></div></div>
 <div class="acc-tab-panel is-active"><div class="acc-detail-grid"><div class="acc-detail"><span>Emitente</span><strong>{{ $tenant->legal_name ?: $tenant->name }}</strong><button class="acc-copy" data-copy="{{ $tenant->legal_name ?: $tenant->name }} | CNPJ: {{ $tenant->cnpj }} | {{ $tenant->full_address }}">Copiar</button></div><div class="acc-detail"><span>Destinatário</span><strong>{{ data_get($snapshot,'recipient.name') }}</strong><button class="acc-copy" data-copy="{{ data_get($snapshot,'recipient.name') }} | Documento: {{ data_get($snapshot,'recipient.document') }} | {{ data_get($snapshot,'recipient.address') }}">Copiar</button></div><div class="acc-detail"><span>Período</span><strong>{{ data_get($snapshot,'identity.period.from') }} a {{ data_get($snapshot,'identity.period.to') }}</strong></div></div></div>
 <div class="acc-table-wrap" style="display:block"><table class="acc-table"><thead><tr><th>Produto</th><th>Quantidade</th><th>Unidade</th><th>Preço</th><th>Total</th></tr></thead><tbody>@foreach(data_get($snapshot,'lines',[]) as $line)<tr><td>{{ data_get($line,'product.name') }}</td><td>{{ number_format((float)data_get($line,'quantity'),3,',','.') }}</td><td>{{ data_get($line,'product.unit') }}</td><td>R$ {{ number_format((float)data_get($line,'unit_price'),2,',','.') }}</td><td>R$ {{ number_format((float)data_get($line,'gross'),2,',','.') }}</td></tr>@endforeach</tbody></table></div>
 <div class="acc-action-box"><div class="acc-detail-grid"><div class="acc-detail"><span>Bruto autorizado</span><strong>R$ {{ number_format((float)data_get($snapshot,'totals.gross'),2,',','.') }}</strong></div><div class="acc-detail"><span>Ajustes</span><strong>R$ {{ number_format((float)data_get($snapshot,'totals.fees'),2,',','.') }}</strong></div><div class="acc-detail"><span>Total autorizado</span><strong>R$ {{ number_format((float)data_get($snapshot,'totals.net'),2,',','.') }}</strong></div></div>@if($gate['profile']->standard_notes)<div class="acc-detail"><span>Observação</span><strong>{{ $gate['profile']->standard_notes }}</strong><button class="acc-copy" data-copy="{{ $gate['profile']->standard_notes }}">Copiar</button></div>@endif</div></section>
</main>@endsection
@push('scripts')<script>document.addEventListener('click',async e=>{const b=e.target.closest('[data-copy]');if(!b)return;try{await navigator.clipboard.writeText(b.dataset.copy);b.textContent='Copiado';setTimeout(()=>b.textContent='Copiar',1200)}catch{const t=document.createElement('textarea');t.value=b.dataset.copy;document.body.append(t);t.select();document.execCommand('copy');t.remove();b.textContent='Copiado'}})</script>@endpush
