@php
$tenant = $sheet->tenant;
$logoPath = null;
if ($tenant && $tenant->logo) {
    $raw = trim($tenant->logo);
    $candidate = public_path('storage/'.ltrim($raw,'/'));
    $logoPath = file_exists($candidate) ? $candidate : null;
}
$rows = collect($snapshot['rows'] ?? []);
$detailed = ($snapshot['grouping_mode'] ?? '') === 'organization_detailed';
$fmtQty = static fn ($value) => rtrim(rtrim(number_format((float)$value,4,',','.'),'0'),',');
@endphp
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><style>
@page{size:A4 portrait;margin:14mm 13mm 15mm}*{box-sizing:border-box}body{font-family:'DejaVu Sans',Arial,sans-serif;color:#111;font-size:9.5pt;margin:0}.header{display:table;width:100%;border-bottom:2px solid #111;padding-bottom:7px}.logo,.identity,.document{display:table-cell;vertical-align:top}.logo{width:58px}.logo img{width:50px;height:50px;object-fit:contain}.identity{padding-left:7px}.identity strong{display:block;font-size:10.5pt;text-transform:uppercase}.identity span{display:block;font-size:8pt;color:#444;margin-top:3px}.document{text-align:right}.document strong{display:block;font-size:12pt}.document span{display:block;font-size:8pt;margin-top:3px}.warning{margin:8px 0;padding:6px;border:1.5px solid #111;text-align:center;font-weight:bold;font-size:9pt;letter-spacing:.25px}.meta{display:table;width:100%;background:#f3f4f6;border-left:3px solid #111;padding:6px 8px;margin:8px 0}.meta-cell{display:table-cell;width:50%;padding-right:10px}.label{display:block;color:#555;font-size:7.5pt;text-transform:uppercase}.value{font-weight:bold;font-size:9pt}.section{font-weight:bold;text-transform:uppercase;border-left:3px solid #111;padding-left:6px;margin:10px 0 6px}table{width:100%;border-collapse:collapse}thead{display:table-header-group}tr{page-break-inside:avoid}th{background:#e5e7eb;border:1px solid #bbb;padding:5px;text-align:left;font-size:8pt}td{border:1px solid #d2d2d2;padding:5px;font-size:8.5pt}.right{text-align:right}.conference{page-break-inside:avoid;margin-top:12px}.choices{display:table;width:100%;border:1px solid #aaa;padding:8px}.choice{display:table-cell;width:33.33%;font-weight:bold}.box{border:1px solid #999;height:78px;padding:6px}.signature{display:table;width:100%;margin-top:10px}.sig-left,.sig-right{display:table-cell;width:50%;vertical-align:top;padding-right:12px}.line{margin-top:14px;border-bottom:1px solid #222;height:14px;font-size:8pt}.footer{position:fixed;bottom:-9mm;left:0;right:0;text-align:center;border-top:1px solid #bbb;padding-top:3px;font-size:7.5pt;color:#555}.pagenum:before{content:counter(page)}
@include('pdf.partials.theme')
</style></head><body>
<div class="footer">SGC · Folha de Conferência de Entregas · Página <span class="pagenum"></span></div>
<div class="header"><div class="logo">@if($logoPath)<img src="{{ $logoPath }}">@endif</div><div class="identity"><strong>{{ data_get($snapshot,'tenant.name') }}</strong><span>@if($tenant?->cnpj)CNPJ: {{ $tenant->cnpj }}<br>@endif{{ $tenant?->city }}@if($tenant?->state) / {{ $tenant->state }}@endif</span></div><div class="document"><strong>FOLHA DE CONFERÊNCIA<br>DE ENTREGAS</strong><span>{{ data_get($snapshot,'sheet.number') ?: 'PRÉ-VISUALIZAÇÃO' }} · Revisão {{ data_get($snapshot,'sheet.revision',1) }}</span><span>Emissão: {{ $sheet->issued_at?->format('d/m/Y H:i') ?? now()->format('d/m/Y H:i') }}</span></div></div>
<div class="warning">DOCUMENTO DE CONFERÊNCIA — SEM VALOR FISCAL</div>
<div class="meta"><div class="meta-cell"><span class="label">Projeto</span><span class="value">{{ data_get($snapshot,'project.title') }}</span></div><div class="meta-cell"><span class="label">Destinatário</span><span class="value">{{ data_get($snapshot,'recipient.name') }}</span></div></div>
<div class="meta"><div class="meta-cell"><span class="label">Período das distribuições</span><span class="value">{{ \Carbon\Carbon::parse(data_get($snapshot,'period.start'))->format('d/m/Y') }} a {{ \Carbon\Carbon::parse(data_get($snapshot,'period.end'))->format('d/m/Y') }}</span></div><div class="meta-cell"><span class="label">Apresentação</span><span class="value">{{ $sheet->grouping_mode->label() }}</span></div></div>
<div class="section">Produtos e quantidades distribuídas</div><table><thead><tr>@if($detailed)<th style="width:30%">Cliente</th>@endif<th>Produto</th><th style="width:16%">Unidade</th><th class="right" style="width:22%">Quantidade distribuída</th></tr></thead><tbody>@foreach($rows as $row)<tr>@if($detailed)<td>{{ data_get($row,'customer.name') }}</td>@endif<td>{{ data_get($row,'product.name') }}</td><td>{{ $row['unit'] }}</td><td class="right">{{ $fmtQty($row['quantity']) }}</td></tr>@endforeach</tbody></table>
<div class="conference"><div class="section">Resultado da conferência</div><div class="choices"><div class="choice">☐ APROVADO</div><div class="choice">☐ CORREÇÃO NECESSÁRIA</div><div class="choice">☐ REJEITADO</div></div><div class="section">Observações / correções</div><div class="box"></div><div class="section">Responsável pela conferência</div><div class="signature"><div class="sig-left"><div class="line">Nome:</div><div class="line">Cargo/Função:</div></div><div class="sig-right"><div class="line">Data: ____ / ____ / ______</div><div class="line">Assinatura:</div></div></div></div>
</body></html>
