@extends('layouts.bento')
@section('title',$order->number) @section('page-title',$order->service->name) @section('user-role','Prestador')
@php($tenantSlug=request()->route('tenant')->slug) @php($bentoNavigation=\App\Support\PortalNavigation::make('provider','orders',$tenantSlug))
@section('content')
<section class="bento-card col-span-full"><div style="display:flex;justify-content:space-between;gap:1rem;flex-wrap:wrap"><div><strong>{{$order->number}}</strong><p>{{$order->beneficiary_snapshot['name']??'Sem beneficiário'}} · {{$order->location}}</p></div><span>{{$order->operational_status}}</span></div></section>
@if(in_array($order->execution->status,['draft','rejected']))<section class="bento-card col-span-full"><h2>Iniciar serviço</h2><form method="post" action="{{route('provider.orders.start',[$tenantSlug,$order])}}" style="display:grid;gap:1rem">@csrf<input type="hidden" name="operation_key" value="{{\Illuminate\Support\Str::uuid()}}">@include('provider._service-fields',['execution'=>$order->execution,'phase'=>'start'])<button class="btn btn-primary">Iniciar</button></form></section>@endif
@if($order->execution->status==='in_progress')<section class="bento-card col-span-full"><h2>Finalizar serviço</h2><form method="post" action="{{route('provider.orders.submit',[$tenantSlug,$order])}}" style="display:grid;gap:1rem">@csrf<input type="hidden" name="operation_key" value="{{\Illuminate\Support\Str::uuid()}}">@include('provider._service-fields',['execution'=>$order->execution,'phase'=>'execution'])@include('provider._service-fields',['execution'=>$order->execution,'phase'=>'finish'])<button class="btn btn-primary">Finalizar serviço</button></form></section>@endif
@if(!$order->execution->isFrozen())<section class="bento-card col-span-full"><h2>Evidências</h2>@foreach(collect(data_get($order->execution->catalog_snapshot,'fields',[]))->whereIn('type',['image','file','signature']) as $field)<form method="post" enctype="multipart/form-data" action="{{route('provider.orders.evidences.store',[$tenantSlug,$order])}}" style="display:flex;gap:.5rem;align-items:end;margin:.75rem 0">@csrf<input type="hidden" name="field_key" value="{{$field['key']}}"><label>{{$field['label']}}<input type="file" name="file" accept="{{$field['type']==='image'?'image/*':'image/*,application/pdf'}}" @if($field['type']==='image') capture="environment" @endif required></label><button class="btn btn-outline">Anexar</button></form>@endforeach</section>@endif
@if($order->execution->evidences->isNotEmpty())<section class="bento-card col-span-full"><h2>Arquivos</h2><ul>@foreach($order->execution->evidences as $evidence)<li><a href="{{route('provider.evidences.download',[$tenantSlug,$evidence])}}">{{$evidence->document->name}}</a></li>@endforeach</ul></section>@endif
@endsection
