@extends('layouts.bento')
@section('title','Serviços') @section('page-title',($operator??false)?'Operação de serviços':'Meus serviços') @section('user-role',($operator??false)?'Operação de serviços':'Prestador')
@php($tenantSlug=request()->route('tenant')->slug) @php($bentoNavigation=\App\Support\PortalNavigation::make('provider','dashboard',$tenantSlug))
@section('content')
<style>.svc-list{display:grid;gap:.75rem}.svc-row{display:grid;grid-template-columns:8rem 1fr auto;gap:1rem;align-items:center;padding:1rem;border-bottom:1px solid #e2e8f0}.svc-summary{display:flex;gap:1.5rem;flex-wrap:wrap}.svc-summary>div{min-width:9rem}.svc-bottom{display:none}@media(max-width:700px){.svc-row{grid-template-columns:1fr;padding:1rem;border:1px solid #e2e8f0;border-radius:1rem}.svc-bottom{display:flex;position:fixed;bottom:0;left:0;right:0;background:white;border-top:1px solid #e2e8f0;justify-content:space-around;padding:.6rem;z-index:20}.svc-bottom a{display:grid;justify-items:center;font-size:.75rem}}</style>
<div class="bento-card col-span-full"><div class="svc-summary"><div><small>{{($operator??false)?'Devido aos prestadores':'A receber'}}</small><strong style="display:block">R$ {{number_format($due,2,',','.')}}</strong></div><div><small>Pago</small><strong style="display:block;color:var(--ws-green,#168a4d)">R$ {{number_format($paid,2,',','.')}}</strong></div><div><small>Saldo</small><strong style="display:block;color:var(--ws-amber,#c87408)">R$ {{number_format($balance,2,',','.')}}</strong></div></div></div>
<section class="bento-card col-span-full"><h2>Visão rápida</h2><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(10rem,1fr));gap:.75rem"><div style="padding:.85rem;border:1px solid #e2e8f0;border-radius:.75rem"><small>Agendadas hoje</small><strong style="display:block;font-size:1.5rem">{{$today->count()}}</strong></div><div style="padding:.85rem;border:1px solid #e2e8f0;border-radius:.75rem"><small>Em andamento ou revisão</small><strong style="display:block;font-size:1.5rem">{{$pending->count()}}</strong></div><div style="padding:.85rem;border:1px solid #e2e8f0;border-radius:.75rem"><small>Próximas</small><strong style="display:block;font-size:1.5rem">{{$upcoming->count()}}</strong></div></div><div style="display:flex;gap:.6rem;flex-wrap:wrap;margin-top:1rem"><a class="btn btn-primary" href="{{route('provider.orders.create',$tenantSlug)}}">Nova ordem</a><a class="btn" href="{{route('provider.orders',$tenantSlug)}}">Ver todas as ordens</a><a class="btn" href="{{route('provider.financial',$tenantSlug)}}">Financeiro</a>@if(auth()->user()->checkPermissionTo('simulate_services'))<a class="btn" href="{{route('services.simulations.index',$tenantSlug)}}">Simulador</a>@endif @if(auth()->user()->checkPermissionTo('manage_service_expenses'))<a class="btn" href="{{route('provider.expenses',$tenantSlug)}}">Registrar despesa</a>@endif</div></section>
@foreach(['Hoje'=>$today,'Próximos'=>$upcoming,'Pendentes'=>$pending] as $label=>$items) @if($items->isNotEmpty())<section class="bento-card col-span-full"><h2>{{$label}}</h2><div class="svc-list">@foreach($items as $order)<div class="svc-row"><time>{{$order->scheduled_at?->format('d/m H:i')}}</time><div><strong>{{$order->service->name}}</strong><div>{{$order->beneficiary_snapshot['name']??'Sem beneficiário'}} · {{$order->location}}</div></div><a class="btn btn-primary" href="{{route('provider.orders.show',[$tenantSlug,$order])}}">{{in_array($order->operational_status,['scheduled','draft'])?'Iniciar':'Ver'}}</a></div>@endforeach</div></section>@endif @endforeach
<nav class="svc-bottom"><a href="{{route('provider.dashboard',$tenantSlug)}}">⌂<span>Início</span></a><a href="{{route('provider.orders',$tenantSlug)}}">☷<span>Serviços</span></a><a href="{{route('provider.financial',$tenantSlug)}}">$<span>Financeiro</span></a><a href="{{route('profile.show',$tenantSlug)}}">○<span>Perfil</span></a></nav>
@endsection
