@php
    $details = collect($summary['details']);
    $compositionRows = $details->flatMap(fn($row) => collect($row['composition'])->map(fn($line) => ['os'=>$row['number']] + $line));
    $fieldRows = $details->flatMap(fn($row) => collect($row['fields'])->map(fn($value,$label) => ['os'=>$row['number'],'label'=>$label,'value'=>$value]));
    $paymentRows = $details->flatMap(fn($row) => collect($row['payments'])->map(fn($payment) => ['os'=>$row['number']] + $payment));
    $resourceRows = $details->flatMap(fn($row) => collect($row['resources'])->map(fn($resource) => ['os'=>$row['number']] + $resource));
@endphp
<div style="display:grid;gap:1rem;max-width:100%">
    <table style="width:100%;border-collapse:collapse"><thead><tr><th>Período</th><th>Execuções</th><th>Recebimentos</th><th>Pagamentos a prestadores</th><th>Despesas de serviços</th><th>Despesas pagas</th></tr></thead><tbody><tr><td>{{$summary['from']}} a {{$summary['to']}}</td><td>{{$summary['executions']}}</td><td>R$ {{number_format($summary['cash_received_period'],2,',','.')}}</td><td>R$ {{number_format($summary['cash_paid_period'],2,',','.')}}</td><td>R$ {{number_format($summary['service_expense_total']??0,2,',','.')}}</td><td>R$ {{number_format($summary['service_expense_paid']??0,2,',','.')}}</td></tr></tbody></table>

    @if($summary['payments_without_cash'])<p role="alert" style="padding:.6rem;background:#fef2f2;color:#991b1b">Conciliação: {{$summary['payments_without_cash']}} pagamento(s) sem movimento de caixa vinculado.</p>@endif

    <h2>Resumo mensal</h2><div style="overflow-x:auto"><table style="width:100%;border-collapse:collapse"><thead><tr><th>Mês</th><th>Execuções</th><th>Quantidades</th><th>A receber</th><th>Recebido</th><th>Saldo cliente</th><th>Devido prestador</th><th>Pago prestador</th><th>Saldo prestador</th></tr></thead><tbody>@foreach($summary['monthly'] as $row)<tr><td>{{$row['month']}}</td><td>{{$row['executions']}}</td><td>@foreach($row['quantities'] as $unit=>$qty){{$qty}} {{$unit}}<br>@endforeach</td>@foreach(['service_value','received','receivable_balance','provider_due','provider_paid','provider_balance'] as $key)<td>R$ {{number_format($row[$key],2,',','.')}}</td>@endforeach</tr>@endforeach</tbody></table></div>

    <h2>Ordens e saldos</h2><div style="overflow-x:auto"><table style="width:100%;border-collapse:collapse"><thead><tr><th>OS</th><th>Data</th><th>Serviço</th><th>Beneficiário</th><th>Prestador</th><th>Quantidade</th><th>Cobrança</th><th>Recebido</th><th>Saldo</th><th>Prestador devido</th><th>Pago</th><th>Saldo</th></tr></thead><tbody>@forelse($details as $row)<tr><td>{{$row['number']}}</td><td>{{$row['date']}}</td><td>{{$row['service']}}</td><td>{{$row['beneficiary']}}</td><td>{{$row['provider']}}</td><td>{{$row['quantity']}} {{$row['unit']}}</td><td>R$ {{number_format($row['service_value'],2,',','.')}}</td><td>R$ {{number_format($row['received'],2,',','.')}}</td><td>R$ {{number_format($row['receivable_balance'],2,',','.')}}</td><td>R$ {{number_format($row['provider_due'],2,',','.')}}</td><td>R$ {{number_format($row['provider_paid'],2,',','.')}}</td><td>R$ {{number_format($row['provider_balance'],2,',','.')}}</td></tr>@empty<tr><td colspan="12">Nenhuma execução validada.</td></tr>@endforelse</tbody></table></div>

    <h2>Origem dos cálculos</h2><div style="overflow-x:auto"><table style="width:100%;border-collapse:collapse"><thead><tr><th>OS</th><th>Composição</th><th>Destino</th><th>Fórmula aplicada</th><th>Valor</th></tr></thead><tbody>@forelse($compositionRows as $line)<tr><td>{{$line['os']}}</td><td>{{$line['description']}}</td><td>{{$line['direction']==='payable'?'Prestador':'Organização'}}</td><td>{{data_get($line,'rule_snapshot.formula')?:(($line['quantity']??0).' × '.($line['unit_price']??0))}}</td><td>{{($line['amount']??0)<0?'− ':''}}R$ {{number_format(abs($line['amount']),2,',','.')}}</td></tr>@empty<tr><td colspan="5">Nenhuma composição.</td></tr>@endforelse</tbody></table></div>

    @if($fieldRows->isNotEmpty())<h2>Dados operacionais informados</h2><div style="overflow-x:auto"><table style="width:100%;border-collapse:collapse"><thead><tr><th>OS</th><th>Campo</th><th>Valor</th></tr></thead><tbody>@foreach($fieldRows as $field)<tr><td>{{$field['os']}}</td><td>{{$field['label']}}</td><td>{{is_scalar($field['value'])?$field['value']:json_encode($field['value'],JSON_UNESCAPED_UNICODE)}}</td></tr>@endforeach</tbody></table></div>@endif

    @if($paymentRows->isNotEmpty())<h2>Movimentos de pagamento</h2><div style="overflow-x:auto"><table style="width:100%;border-collapse:collapse"><thead><tr><th>OS</th><th>Data</th><th>Destino</th><th>Método</th><th>Valor</th><th>Movimento de caixa</th></tr></thead><tbody>@foreach($paymentRows as $payment)<tr><td>{{$payment['os']}}</td><td>{{$payment['date']}}</td><td>{{$payment['direction']==='payable'?'Prestador':'Organização'}}</td><td>{{$payment['method']}}</td><td>R$ {{number_format($payment['amount'],2,',','.')}}</td><td>{{$payment['cash_movement_id']??'Não vinculado'}}</td></tr>@endforeach</tbody></table></div>@endif

    @if($resourceRows->isNotEmpty())<h2>Recursos e insumos</h2><div style="overflow-x:auto"><table style="width:100%;border-collapse:collapse"><thead><tr><th>OS</th><th>Descrição</th><th>Efeito</th><th>Valor</th><th>Despesa</th></tr></thead><tbody>@foreach($resourceRows as $resource)<tr><td>{{$resource['os']}}</td><td>{{$resource['description']}}</td><td>{{$resource['effect']}}</td><td>R$ {{number_format($resource['amount'],2,',','.')}}</td><td>{{$resource['expense_id']??'—'}}</td></tr>@endforeach</tbody></table></div>@endif

    <h2>Despesas do módulo de serviços</h2><div style="overflow-x:auto"><table style="width:100%;border-collapse:collapse"><thead><tr><th>Data</th><th>Origem</th><th>Descrição</th><th>Categoria</th><th>Total</th><th>Pago</th><th>Situação</th></tr></thead><tbody>@forelse($summary['service_expenses']??[] as $expense)<tr><td>{{$expense['date']}}</td><td>{{$expense['origin']}}</td><td>{{$expense['description']}}</td><td>{{$expense['category']}}</td><td>R$ {{number_format($expense['amount'],2,',','.')}}</td><td>R$ {{number_format($expense['paid'],2,',','.')}}</td><td>{{$expense['status']}}</td></tr>@empty<tr><td colspan="7">Nenhuma despesa de serviço no período.</td></tr>@endforelse</tbody></table></div>
</div>
