<fieldset class="financial-rule" data-rule style="border:1px solid #cbd5e1;border-radius:.75rem;padding:1rem;margin-bottom:.75rem">
    <legend><strong>Termo adicional</strong></legend>
    <div class="config-grid">
        <label>Descrição<input name="financial_config[rules][{{ $index }}][description]" value="{{ $rule['description'] ?? '' }}" required placeholder="Ex.: Desconto do óleo fornecido"></label>
        <label>Este termo altera<select name="financial_config[rules][{{ $index }}][direction]" required><option value="receivable" @selected(($rule['direction'] ?? '') === 'receivable')>Valor a receber pela organização</option><option value="payable" @selected(($rule['direction'] ?? '') === 'payable')>Valor a pagar ao prestador</option></select></label>
        <label>Como calcular<select name="financial_config[rules][{{ $index }}][method]" required><option value="fixed_addition" @selected(($rule['method'] ?? '') === 'fixed_addition')>Valor fixo ou informado</option><option value="fixed_deduction" @selected(($rule['method'] ?? '') === 'fixed_deduction')>Valor fixo ou informado (legado)</option><option value="quantity_x_rate" @selected(($rule['method'] ?? '') === 'quantity_x_rate')>Quantidade × tarifa</option><option value="percent_addition" @selected(($rule['method'] ?? '') === 'percent_addition')>Percentual do valor base</option><option value="percent_deduction" @selected(($rule['method'] ?? '') === 'percent_deduction')>Percentual do valor base (legado)</option></select></label>
        <label>Efeito<select name="financial_config[rules][{{ $index }}][effect]" required><option value="add" @selected(($rule['effect'] ?? '') === 'add')>Acrescentar</option><option value="subtract" @selected(($rule['effect'] ?? '') === 'subtract')>Descontar</option></select></label>
        <label>Valor fixo ou tarifa<input type="number" step="0.0001" min="0" name="financial_config[rules][{{ $index }}][value]" value="{{ $rule['value'] ?? 0 }}"></label>
        <label>Percentual<input type="number" step="0.0001" min="0" max="100" name="financial_config[rules][{{ $index }}][percentage]" value="{{ $rule['percentage'] ?? 0 }}"></label>
        <label>Usar valor deste campo<select name="financial_config[rules][{{ $index }}][value_field]"><option value="">Não usar</option>@foreach($numericFields as $field)<option value="{{ $field->key }}" @selected(($rule['value_field'] ?? '') === $field->key)>{{ $field->label }}</option>@endforeach</select></label>
        <label>Usar quantidade deste campo<select name="financial_config[rules][{{ $index }}][quantity_field]"><option value="">Não usar</option>@foreach($numericFields as $field)<option value="{{ $field->key }}" @selected(($rule['quantity_field'] ?? '') === $field->key)>{{ $field->label }}</option>@endforeach</select></label>
        <label>Ou criar campo — identificador<input name="financial_config[rules][{{ $index }}][input_key]" value="{{ $rule['input_key'] ?? '' }}" pattern="[a-z][a-z0-9_]*" placeholder="litros_oleo"></label>
        <label>Nome mostrado do novo campo<input name="financial_config[rules][{{ $index }}][input_label]" value="{{ $rule['input_label'] ?? '' }}" placeholder="Litros de óleo fornecido"></label>
        <label>O novo campo informa<select name="financial_config[rules][{{ $index }}][input_role]"><option value="quantity" @selected(($rule['input_role'] ?? 'quantity') === 'quantity')>Quantidade</option><option value="value" @selected(($rule['input_role'] ?? '') === 'value')>Valor ou percentual</option></select></label>
        <label>Unidade do novo campo<input name="financial_config[rules][{{ $index }}][input_unit]" value="{{ $rule['input_unit'] ?? '' }}" placeholder="litro, km, hora"></label>
        <label>Quando preencher<select name="financial_config[rules][{{ $index }}][input_phase]"><option value="start" @selected(($rule['input_phase'] ?? '') === 'start')>Ao iniciar</option><option value="execution" @selected(($rule['input_phase'] ?? '') === 'execution')>Durante a execução</option><option value="finish" @selected(($rule['input_phase'] ?? 'finish') === 'finish')>Ao concluir</option></select></label>
        <label><input type="checkbox" name="financial_config[rules][{{ $index }}][input_required]" value="1" @checked($rule['input_required'] ?? false)> Preenchimento obrigatório</label>
        <label><input type="checkbox" name="financial_config[rules][{{ $index }}][evidence_required]" value="1" @checked($rule['evidence_required'] ?? false)> Exigir comprovante quando houver valor</label>
        <label>Identificador do comprovante<input name="financial_config[rules][{{ $index }}][evidence_key]" value="{{ $rule['evidence_key'] ?? '' }}" pattern="[a-z][a-z0-9_]*" placeholder="comprovante_oleo"></label>
        <label>Nome do comprovante<input name="financial_config[rules][{{ $index }}][evidence_label]" value="{{ $rule['evidence_label'] ?? '' }}" placeholder="Nota ou foto do óleo"></label>
        <label>Ou usar comprovante já cadastrado<select name="financial_config[rules][{{ $index }}][evidence_field]"><option value="">Criar automaticamente ou não usar</option>@foreach($evidenceFields as $field)<option value="{{ $field->key }}" @selected(($rule['evidence_field'] ?? '') === $field->key)>{{ $field->label }}</option>@endforeach</select></label>
    </div>
    <button type="button" class="btn btn-outline" data-remove-rule>Remover termo</button>
</fieldset>
