@extends('layouts.bento')
@section('title', $version->service->name)
@section('page-title', $version->service->name.' · versão '.$version->version)
@section('user-role', 'Catálogo')
@php($tenantSlug=request()->route('tenant')->slug)
@php($bentoNavigation=\App\Support\PortalNavigation::make('services','catalog',$tenantSlug))
@section('content')
<section class="bento-card col-span-full"><div style="display:flex;justify-content:space-between;gap:1rem"><div><h2>Versão {{$version->version}}</h2><p>{{$version->status}} · {{$version->unit}} · conferência {{$version->review_mode}}</p></div><div style="display:flex;gap:.5rem"><a class="btn btn-outline" href="{{route('services.catalog.preview',[$tenantSlug,$version])}}">Visualizar como prestador</a><form method="post" action="{{route('services.catalog.clone',[$tenantSlug,$version])}}">@csrf<button class="btn btn-outline">Duplicar versão</button></form>@if($version->status==='draft')<form method="post" action="{{route('services.catalog.publish',[$tenantSlug,$version])}}">@csrf<button class="btn btn-primary">Publicar</button></form>@endif</div></div></section>
@if($version->status==='draft')
<section class="bento-card col-span-full"><h2>Configuração financeira e operacional</h2><form method="post" action="{{route('services.catalog.update',[$tenantSlug,$version])}}" style="display:grid;grid-template-columns:repeat(auto-fit,minmax(13rem,1fr));gap:.75rem">@csrf @method('put')<label>Unidade<input name="unit" value="{{$version->unit}}" required></label><label>Conferência<select name="review_mode"><option value="manual" @selected($version->review_mode==='manual')>Manual</option><option value="automatic" @selected($version->review_mode==='automatic')>Automática</option></select></label><label><input type="checkbox" name="allow_provider_create_order" value="1" @checked($version->allow_provider_create_order)> Prestador pode criar OS</label><label><input type="checkbox" name="receivable_enabled" value="1" @checked($version->receivable_enabled)> Gerar conta a receber</label><label>Cobrança do cliente<select name="customer_pricing_method"><option value="fixed">Valor fixo</option><option value="quantity_x_rate" @selected($version->customer_pricing_method==='quantity_x_rate')>Quantidade × tarifa</option><option value="percent_of_base" @selected($version->customer_pricing_method==='percent_of_base')>Percentual</option></select></label><label>Tarifa/valor cliente<input type="number" step="0.0001" name="customer_rate" value="{{$version->customer_rate}}"></label><label>Percentual cliente<input type="number" step="0.0001" name="customer_percentage" value="{{$version->customer_percentage}}"></label><label><input type="checkbox" name="payable_enabled" value="1" @checked($version->payable_enabled)> Gerar valor devido ao prestador</label><label>Cálculo do prestador<select name="provider_pricing_method"><option value="">Escolha</option><option value="fixed" @selected($version->provider_pricing_method==='fixed')>Valor fixo</option><option value="quantity_x_rate" @selected($version->provider_pricing_method==='quantity_x_rate')>Quantidade × tarifa</option><option value="percent_of_base" @selected($version->provider_pricing_method==='percent_of_base')>Percentual do valor do serviço</option></select></label><label>Tarifa/valor padrão prestador<input type="number" step="0.0001" name="default_provider_rate" value="{{$version->default_provider_rate}}"></label><label>Percentual padrão prestador<input type="number" step="0.0001" name="provider_percentage" value="{{$version->provider_percentage}}"></label><button class="btn btn-primary">Salvar rascunho</button></form></section>
@endif
<section class="bento-card col-span-full"><h2>Campos da execução</h2><table style="width:100%"><thead><tr><th>Etapa</th><th>Campo</th><th>Tipo</th><th>Obrigatório</th><th>Relatório</th><th></th></tr></thead><tbody>@foreach($version->fields as $field)<tr><td>{{$field->phase}}</td><td>{{$field->label}} <small>({{$field->key}})</small></td><td>{{$field->type}}</td><td>{{$field->required?'Sim':'Não'}}</td><td>{{$field->reportable?'Sim':'Não'}}</td><td>@if($version->status==='draft')<form method="post" action="{{route('services.catalog.fields.delete',[$tenantSlug,$version,$field])}}">@csrf @method('delete')<button class="btn btn-outline">Remover</button></form>@endif</td></tr>@endforeach</tbody></table>@if($version->status==='draft')<h3>Adicionar campo</h3><form method="post" action="{{route('services.catalog.fields.store',[$tenantSlug,$version])}}" style="display:grid;grid-template-columns:repeat(auto-fit,minmax(12rem,1fr));gap:.75rem">@csrf<input name="key" required pattern="[a-z][a-z0-9_]*" placeholder="chave_do_campo"><input name="label" required placeholder="Nome mostrado"><select name="type">@foreach(\App\Models\ServiceVersionField::TYPES as $type)<option>{{$type}}</option>@endforeach</select><select name="phase">@foreach(\App\Models\ServiceVersionField::PHASES as $phase)<option>{{$phase}}</option>@endforeach</select><input name="section" placeholder="Seção"><input name="unit" placeholder="Unidade"><input type="number" name="minimum" step="0.0001" placeholder="Mínimo"><input type="number" name="maximum" step="0.0001" placeholder="Máximo"><textarea name="options_text" placeholder="Opções, uma por linha"></textarea><label><input type="checkbox" name="required" value="1"> Obrigatório</label><label><input type="checkbox" name="visible_to_provider" value="1" checked> Visível ao prestador</label><label><input type="checkbox" name="editable_by_provider" value="1" checked> Editável pelo prestador</label><label><input type="checkbox" name="visible_to_management" value="1" checked> Visível à gestão</label><label><input type="checkbox" name="include_in_documents" value="1"> Incluir em documentos</label><label><input type="checkbox" name="reportable" value="1"> Incluir em relatórios</label><button class="btn btn-primary">Adicionar campo</button></form>@endif</section>
<section class="bento-card col-span-full"><h2>Remuneração do prestador</h2><p>Precedência: tarifa específica abaixo; depois tarifa padrão da versão. Sem tarifa válida, a aprovação é bloqueada.</p>@if($version->status==='draft')<form method="post" action="{{route('services.catalog.rates.store',[$tenantSlug,$version])}}" style="display:flex;gap:.5rem;flex-wrap:wrap">@csrf<select name="service_provider_id" required>@foreach($providers as $provider)<option value="{{$provider->id}}">{{$provider->name}}</option>@endforeach</select><select name="calculation_method"><option value="quantity_x_rate">Quantidade × tarifa</option><option value="fixed">Valor fixo</option><option value="percent_of_base">Percentual do base</option></select><input type="number" step="0.0001" name="rate" placeholder="Tarifa"><input type="number" step="0.01" name="fixed_amount" placeholder="Valor fixo"><input type="number" step="0.0001" name="percentage" placeholder="Percentual"><button class="btn btn-primary">Salvar override</button></form>@endif<ul>@foreach($version->providerRates as $rate)<li>{{$rate->provider->name}}: {{$rate->calculation_method}} · tarifa {{$rate->rate}} · fixo {{$rate->fixed_amount}} · {{$rate->percentage}}%</li>@endforeach</ul></section>
@endsection
