@extends('layouts.bento')
@section('title','Nova ordem') @section('page-title','Nova ordem de serviço') @section('user-role','Workspace')
@php($tenantSlug=request()->route('tenant')->slug) @php($bentoNavigation=\App\Support\PortalNavigation::make('services','new',$tenantSlug))
@section('content')
<section class="bento-card col-span-full">
<form method="post" action="{{route('services.management.store',$tenantSlug)}}" style="max-width:48rem;display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,18rem),1fr));gap:1rem">
@csrf
<label style="grid-column:1/-1">Serviço<select id="service-version" name="service_version_id" required><option value="">Selecione</option>@foreach($versions as $version)<option value="{{$version->id}}" data-service="{{$version->service_id}}" data-members-only="{{$version->members_only?'1':'0'}}" @selected(old('service_version_id')==$version->id)>{{$version->service->name}} — v{{$version->version}}{{$version->members_only?' · somente membros':''}}</option>@endforeach</select></label>
<label id="associate-label">Membro/associado <span id="associate-required-note" style="color:#64748b">(opcional)</span><select id="associate-select" name="associate_id"><option value="">Sem membro vinculado</option>@foreach($associates as $associate)<option value="{{$associate->id}}" @selected(old('associate_id')==$associate->id)>{{$associate->display_name}}</option>@endforeach</select></label>
<label>Nome ou apelido do beneficiário<input name="beneficiary_name" value="{{old('beneficiary_name')}}" maxlength="191" required></label>
<label>Prestador<select id="service-provider" name="service_provider_id"><option value="">Sem prestador</option>@foreach($providers as $provider)<option value="{{$provider->id}}" data-services="{{$provider->services->pluck('id')->join(',')}}" @selected(old('service_provider_id')==$provider->id)>{{$provider->name}}</option>@endforeach</select><small style="color:#64748b">A lista respeita os serviços habilitados para cada prestador.</small></label>
<label>Data e hora<input type="datetime-local" name="scheduled_at" required value="{{old('scheduled_at',now()->format('Y-m-d\\TH:i'))}}"></label><label>Local<input name="location" value="{{old('location')}}"></label>
@foreach($versions as $version)<div data-version-fields="{{$version->id}}" hidden style="grid-column:1/-1;display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,18rem),1fr));gap:1rem"><strong style="grid-column:1/-1">Dados do serviço</strong>@foreach($version->fields->where('phase','order') as $field)@include('services._order-field',['field'=>$field])@endforeach</div>@endforeach
<button class="btn btn-primary" style="grid-column:1/-1">Criar ordem</button></form></section>
<script>document.addEventListener('DOMContentLoaded',()=>{const s=document.getElementById('service-version'),p=document.getElementById('service-provider'),a=document.getElementById('associate-select'),n=document.getElementById('associate-required-note'),sync=()=>{const selected=s.options[s.selectedIndex],sid=selected?.dataset.service||'',membersOnly=selected?.dataset.membersOnly==='1';a.required=membersOnly;n.textContent=membersOnly?'(obrigatório para este serviço)':'(opcional)';document.querySelectorAll('[data-version-fields]').forEach(el=>{const show=el.dataset.versionFields===s.value;el.hidden=!show;el.style.display=show?'grid':'none';el.querySelectorAll('input,select,textarea').forEach(i=>i.disabled=!show)});[...p.options].forEach((o,i)=>{if(!i)return;const ok=(o.dataset.services||'').split(',').includes(sid);o.hidden=!ok;o.disabled=!ok});if(p.selectedOptions[0]?.disabled)p.value=''};s.addEventListener('change',sync);sync()})</script>
@endsection
