@extends('layouts.bento')
@section('title',$order->number)
@section('page-title','Dossiê '.$order->number)
@section('user-role','Workspace')
@php($tenantSlug=request()->route('tenant')->slug)
@php($bentoNavigation=\App\Support\PortalNavigation::make('services','queue',$tenantSlug))
@section('content')
<section class="bento-card col-span-full"><div style="display:flex;justify-content:space-between"><div><h2>{{$order->service->name}}</h2><p>{{$order->beneficiary_snapshot['name']??'Sem beneficiário'}} · {{$order->provider_snapshot['name']??'Sem prestador'}} · {{$order->location}}</p></div><strong>{{$statuses->resolve($order)}}</strong></div></section>
<section class="bento-card col-span-full"><h2>Execução</h2><dl style="display:grid;grid-template-columns:max-content 1fr;gap:.4rem 1rem">@foreach($order->execution->values??[] as $key=>$value)<dt>{{$key}}</dt><dd>{{is_array($value)?json_encode($value):$value}}</dd>@endforeach</dl>@if($order->execution->status==='submitted')<div style="display:flex;gap:.75rem;margin-top:1rem"><form method="post" action="{{route('services.management.approve',[$tenantSlug,$order])}}">@csrf<input type="hidden" name="operation_key" value="{{\Illuminate\Support\Str::uuid()}}"><button class="btn btn-primary">Aprovar execução</button></form><form method="post" action="{{route('services.management.correction',[$tenantSlug,$order])}}">@csrf<input type="hidden" name="operation_key" value="{{\Illuminate\Support\Str::uuid()}}"><input name="reason" required minlength="5" placeholder="Motivo da correção"><button class="btn btn-outline">Solicitar correção</button></form></div>@endif</section>
@if(!$order->execution->isFrozen())<section class="bento-card col-span-full"><h2>Recursos e efeitos financeiros</h2><form method="post" action="{{route('services.management.resources.store',[$tenantSlug,$order])}}" style="display:grid;grid-template-columns:repeat(auto-fit,minmax(12rem,1fr));gap:.5rem">@csrf<input type="hidden" name="operation_key" value="{{\Illuminate\Support\Str::uuid()}}"><input name="resource_key" required placeholder="Código do recurso"><input name="description" required placeholder="Descrição"><select name="provided_by"><option value="organization">Organização</option><option value="provider">Prestador</option><option value="customer">Cliente</option><option value="third_party">Terceiro</option></select><select name="effect"><option value="information_only">Somente informativo</option><option value="deduct_from_receivable">Descontar do cliente</option><option value="add_to_receivable">Acrescentar ao cliente</option><option value="reimburse_provider">Reembolsar prestador</option><option value="create_association_expense">Gerar despesa da organização</option></select><input type="number" name="quantity" step="0.0001" min="0" placeholder="Quantidade"><input name="unit" placeholder="Unidade"><input type="number" name="unit_price" step="0.0001" min="0" placeholder="Preço unitário"><input type="number" name="amount" step="0.01" min="0" placeholder="Valor total"><button class="btn btn-primary">Registrar recurso</button></form></section>@endif
@if($order->execution->compositionLines->isNotEmpty())<section class="bento-card col-span-full"><h2>Composição e obrigações</h2>@foreach($order->execution->obligations as $obligation)<div style="border-top:1px solid #e2e8f0;padding:1rem 0"><h3>{{$obligation->direction==='payable'?'Organização deve ao prestador':'Cliente deve à organização'}} — {{$obligation->number}}</h3><p>Devido: R$ {{number_format($obligation->total_amount,2,',','.')}} · Pago: R$ {{number_format($obligation->paid_amount,2,',','.')}} · Saldo: R$ {{number_format($obligation->balance,2,',','.')}}</p>@if($obligation->balance>0)<form method="post" action="{{route('services.management.payments.store',[$tenantSlug,$obligation])}}" style="display:flex;gap:.5rem;flex-wrap:wrap">@csrf<input type="hidden" name="operation_key" value="{{\Illuminate\Support\Str::uuid()}}"><input type="number" name="amount" step="0.01" max="{{$obligation->balance}}" min="0.01" required placeholder="Valor"><select name="payment_method"><option value="pix">PIX</option><option value="dinheiro">Dinheiro</option><option value="transferencia">Transferência</option><option value="cheque">Cheque</option><option value="outro">Outro</option></select><select name="bank_account_id"><option value="">Sem movimento de caixa</option>@foreach($accounts as $account)<option value="{{$account->id}}">{{$account->name}}</option>@endforeach</select><input type="date" name="payment_date" value="{{now()->toDateString()}}" required><button class="btn btn-primary">Registrar {{$obligation->direction==='payable'?'pagamento':'recebimento'}}</button></form>@endif<form method="post" action="{{route('services.management.adjustments.store',[$tenantSlug,$obligation])}}" style="display:flex;gap:.5rem;flex-wrap:wrap;margin-top:.5rem">@csrf<input type="hidden" name="operation_key" value="{{\Illuminate\Support\Str::uuid()}}"><input name="type" value="manual" required><input type="number" name="amount" step="0.01" required placeholder="Ajuste (+ ou -)"><input name="reason" minlength="5" required placeholder="Motivo"><button class="btn btn-outline">Registrar ajuste</button></form><ul>@foreach($obligation->allocations as $allocation)<li>R$ {{number_format($allocation->amount,2,',','.')}} em {{$allocation->paymentEvent->payment_date?->format('d/m/Y')}} ({{$allocation->paymentEvent->status}}) @if($allocation->paymentEvent->event_type==='payment'&&$allocation->paymentEvent->status==='confirmed')<form method="post" action="{{route('services.management.payments.reverse',[$tenantSlug,$allocation->paymentEvent])}}" style="display:inline">@csrf<input type="hidden" name="operation_key" value="{{\Illuminate\Support\Str::uuid()}}"><input name="reason" minlength="5" required placeholder="Motivo do estorno"><button class="btn btn-outline">Estornar</button></form>@endif</li>@endforeach</ul></div>@endforeach</section>@endif
<section class="bento-card col-span-full"><h2>Documentos e evidências</h2><ul>@forelse($order->execution->evidences as $evidence)<li><a href="{{route('services.management.evidences.download',[$tenantSlug,$evidence])}}">{{$evidence->document->name}}</a> · SHA-256 {{$evidence->sha256}}</li>@empty<li>Nenhuma evidência.</li>@endforelse</ul></section>
<section class="bento-card col-span-full"><h2>Gerar documentos</h2><div style="display:flex;gap:.5rem">@foreach(['order'=>'Ordem de serviço','execution'=>'Relatório de execução'] as $type=>$label)<form method="post" action="{{route('services.management.documents.generate',[$tenantSlug,$order])}}">@csrf<input type="hidden" name="type" value="{{$type}}"><button class="btn btn-outline">{{$label}}</button></form>@endforeach</div></section>
@endsection
