<?php

namespace App\Filament\Resources\ServiceOrderResource\Pages;

use App\Filament\Resources\ServiceOrderResource;
use Filament\Resources\Pages\CreateRecord;

class CreateServiceOrder extends CreateRecord
{
    protected static string $resource = ServiceOrderResource::class;

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        // Number is auto-generated by ServiceOrder model boot
        $data['created_by'] = auth()->id();

        // Compute final_price and provider_payment when possible
        $data['final_price'] = $data['final_price'] ?? 0;
        $data['provider_payment'] = $data['provider_payment'] ?? 0;

        try {
            if (!empty($data['service_id']) && !empty($data['unit_price']) && !empty($data['actual_quantity'])) {
                $qty = (float) $data['actual_quantity'];
                $data['final_price'] = round($qty * (float) $data['unit_price'], 2);
            }

            if (!empty($data['service_provider_id']) && !empty($data['service_id'])) {
                $ps = \App\Models\ServiceProviderService::where('service_provider_id', $data['service_provider_id'])
                    ->where('service_id', $data['service_id'])->first();
                if ($ps) {
                    $unit = $data['unit'] ?? null;
                    $rate = 0;
                    if ($unit === 'hora') $rate = $ps->provider_hourly_rate ?? 0;
                    elseif (in_array($unit, ['diaria', 'dia'])) $rate = $ps->provider_daily_rate ?? 0;
                    else $rate = $ps->provider_unit_rate ?? 0;

                    $qty = !empty($data['actual_quantity']) ? (float) $data['actual_quantity'] : (!empty($data['quantity']) ? (float) $data['quantity'] : 0);
                    $data['provider_payment'] = round($qty * (float) $rate, 2);
                }
            }
        } catch (\Throwable $e) {
            // ignore and let validations handle issues
        }

        return $data;
    }
}
