@extends('layouts.bento')

@section('title', 'Folhas de Conferência')
@section('page-title', 'Folhas de Conferência')
@section('page-subtitle', 'Conferência operacional das distribuições realizadas')
@section('user-role', 'Entregas')

@php
    $bentoNavigation = \App\Support\PortalNavigation::make('delivery', 'conference', $currentTenant->slug ?? request()->route('tenant'));
    $projectData = $projects->map(function ($project) {
        $customers = $project->customers->filter->status;
        if ($project->customer?->status && ! $customers->contains('id', $project->customer_id)) $customers->prepend($project->customer);
        return [
            'id' => $project->id,
            'customers' => $customers->map(fn ($customer) => ['id' => $customer->id, 'name' => $customer->trade_name ?: $customer->name])->values(),
            'organizations' => $project->organizations->map(fn ($organization) => ['id' => $organization->id, 'name' => $organization->name])->values(),
        ];
    })->keyBy('id');
@endphp

@section('content')
<style>
.fc-page{--fc-green:#168a4d;--fc-border:var(--color-border,#dce7e0);--fc-surface:var(--color-surface,#fff);--fc-soft:var(--color-surface-soft,#f8faf9);--fc-text:var(--color-text,#102018);--fc-muted:var(--color-text-secondary,#607067);display:grid;gap:.85rem;color:var(--fc-text)}
.fc-toolbar,.fc-form,.fc-table-wrap{border:1px solid var(--fc-border);border-radius:15px;background:var(--fc-surface);box-shadow:0 4px 14px rgba(15,35,24,.045)}
.fc-toolbar{display:flex;align-items:center;justify-content:space-between;gap:.8rem;padding:.75rem .85rem}.fc-toolbar h2{margin:0;font-size:1rem}.fc-toolbar p{margin:.15rem 0 0;color:var(--fc-muted);font-size:.82rem}
.fc-btn{display:inline-flex;align-items:center;justify-content:center;gap:.4rem;min-height:40px;padding:.55rem .8rem;border:1px solid var(--fc-border);border-radius:10px;background:#fff;color:var(--fc-text);font-weight:700;text-decoration:none;cursor:pointer}.fc-btn:disabled{opacity:.55;cursor:not-allowed}.fc-btn-primary{border-color:var(--fc-green);background:var(--fc-green);color:#fff}.fc-form{display:none;padding:1rem}.fc-form.open{display:block}.fc-grid{display:grid;grid-template-columns:2fr 1fr 2fr 1fr 1fr;gap:.8rem}.fc-field{display:grid;gap:.3rem}.fc-field label{font-size:.76rem;font-weight:700;color:var(--fc-muted)}.fc-field input,.fc-field select{width:100%;min-height:42px;border:1px solid var(--fc-border);border-radius:9px;background:#fff;padding:.55rem .65rem;color:var(--fc-text)}
.fc-help{grid-column:1/-1;margin:0;color:var(--fc-muted);font-size:.8rem}.fc-actions{grid-column:1/-1;display:flex;justify-content:flex-end;gap:.5rem}.fc-table-wrap{overflow:hidden}.fc-table{width:100%;border-collapse:collapse}.fc-table th{padding:.68rem .72rem;background:var(--fc-soft);border-bottom:1px solid var(--fc-border);text-align:left;font-size:.72rem;text-transform:uppercase;color:var(--fc-muted)}.fc-table td{padding:.72rem;border-bottom:1px solid var(--fc-border);font-size:.86rem;vertical-align:middle}.fc-table tr:last-child td{border-bottom:0}.fc-number{font-weight:800;color:var(--fc-green)}.fc-badge{display:inline-flex;padding:.25rem .48rem;border-radius:99px;background:#eef4f0;font-size:.72rem;font-weight:700}.fc-link{color:var(--fc-green);font-weight:700;text-decoration:none}.fc-mobile{display:none}.fc-empty{padding:2.3rem;text-align:center;color:var(--fc-muted)}
.fc-selection{grid-column:1/-1;border:1px solid var(--fc-border);border-radius:12px;overflow:hidden;background:#fff}.fc-selection-head{display:flex;align-items:center;justify-content:space-between;gap:.7rem;padding:.7rem .75rem;border-bottom:1px solid var(--fc-border);background:var(--fc-soft)}.fc-selection-title{display:grid;gap:.15rem}.fc-selection-title strong{font-size:.9rem}.fc-selection-title span{font-size:.75rem;color:var(--fc-muted)}.fc-quick{display:flex;flex-wrap:wrap;gap:.4rem}.fc-quick .fc-btn{min-height:34px;padding:.38rem .58rem;font-size:.76rem}.fc-selection-summary{display:grid;grid-template-columns:repeat(4,1fr);border-bottom:1px solid var(--fc-border)}.fc-counter{padding:.58rem .7rem;border-right:1px solid var(--fc-border)}.fc-counter:last-child{border:0}.fc-counter small{display:block;color:var(--fc-muted);font-size:.68rem;text-transform:uppercase}.fc-counter strong{font-size:1rem}.fc-counter.warn strong{color:#b45309}.fc-delivery-scroll{max-height:390px;overflow:auto}.fc-delivery-table{width:100%;border-collapse:collapse}.fc-delivery-table th{position:sticky;top:0;z-index:1;padding:.55rem .65rem;background:#f3f7f4;border-bottom:1px solid var(--fc-border);text-align:left;font-size:.68rem;text-transform:uppercase;color:var(--fc-muted)}.fc-delivery-table td{padding:.55rem .65rem;border-bottom:1px solid var(--fc-border);font-size:.8rem}.fc-delivery-table tr.is-blocked{background:#fafafa;color:#8a9690}.fc-delivery-table tr.is-selected{background:#f0faf4}.fc-selection-state{padding:1.6rem;text-align:center;color:var(--fc-muted)}.fc-selection-error{color:#b42318;background:#fff1f0}.fc-check{width:18px;height:18px;accent-color:var(--fc-green)}
@media(max-width:900px){.fc-grid{grid-template-columns:1fr 1fr}.fc-field:first-child,.fc-field:nth-child(3){grid-column:1/-1}.fc-desktop{display:none}.fc-mobile{display:grid;gap:.65rem}.fc-card{display:grid;gap:.5rem;padding:.85rem;border-bottom:1px solid var(--fc-border)}.fc-card:last-child{border-bottom:0}.fc-card-head{display:flex;justify-content:space-between;gap:.5rem}.fc-card-meta{color:var(--fc-muted);font-size:.8rem}.fc-selection-summary{grid-template-columns:1fr 1fr}.fc-counter:nth-child(2){border-right:0}.fc-selection-head{align-items:flex-start;flex-direction:column}}@media(max-width:560px){.fc-toolbar{align-items:flex-start;flex-direction:column}.fc-toolbar .fc-btn{width:100%}.fc-grid{grid-template-columns:1fr}.fc-field{grid-column:1!important}.fc-actions{flex-direction:column}.fc-actions .fc-btn{width:100%}.fc-delivery-table th:nth-child(2),.fc-delivery-table td:nth-child(2){display:none}}
</style>
<div class="fc-page">
    @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
    <div class="fc-toolbar">
        <div><h2>Conferência das entregas distribuídas</h2><p>Documento operacional sem valor fiscal, anterior e independente da cobrança.</p></div>
        @can('create', \App\Models\DeliveryConferenceSheet::class)<button class="fc-btn fc-btn-primary" id="fc-new" type="button"><i class="ph ph-plus"></i> Nova folha</button>@endcan
    </div>

    @can('create', \App\Models\DeliveryConferenceSheet::class)
    <form class="fc-form open" id="fc-form" method="post" action="{{ route('delivery.conference-sheets.store', request()->route('tenant')) }}">
        @csrf
        <div class="fc-grid">
            <div class="fc-field"><label for="fc-project">Projeto</label><select id="fc-project" name="sales_project_id" required><option value="">Selecione</option>@foreach($projects as $project)<option value="{{ $project->id }}" @selected(old('sales_project_id', request()->integer('project'))==$project->id)>{{ $project->title }}</option>@endforeach</select></div>
            <div class="fc-field"><label for="fc-type">Destinatário</label><select id="fc-type" name="recipient_type" required><option value="customer" @selected(old('recipient_type') === 'customer')>Cliente</option><option value="organization" @selected(old('recipient_type') === 'organization')>Organização</option></select></div>
            <div class="fc-field"><label for="fc-recipient">Cliente / organização</label><select id="fc-recipient" name="recipient_id" required disabled><option value="">Escolha o projeto</option></select></div>
            <div class="fc-field"><label for="fc-start">De</label><input id="fc-start" type="date" name="period_start" value="{{ old('period_start', now()->startOfMonth()->format('Y-m-d')) }}" required></div>
            <div class="fc-field"><label for="fc-end">Até</label><input id="fc-end" type="date" name="period_end" value="{{ old('period_end', now()->format('Y-m-d')) }}" required></div>
            <p class="fc-help">A tabela abaixo mostra todas as distribuições aprovadas encontradas. Confira o que será incluído e o que ficará de fora antes de preparar a folha.</p>
            <div class="fc-selection" aria-live="polite">
                <div class="fc-selection-head"><div class="fc-selection-title"><strong>Distribuições do período</strong><span>Selecione exatamente as linhas que devem compor esta folha.</span></div><div class="fc-quick"><button class="fc-btn" id="fc-reload" type="button"><i class="ph ph-arrows-clockwise"></i> Atualizar</button><button class="fc-btn" id="fc-select-all" type="button">Selecionar disponíveis</button><button class="fc-btn" id="fc-select-none" type="button">Limpar seleção</button></div></div>
                <div class="fc-selection-summary"><div class="fc-counter"><small>Encontradas</small><strong id="fc-total">0</strong></div><div class="fc-counter"><small>Disponíveis</small><strong id="fc-available">0</strong></div><div class="fc-counter"><small>Selecionadas</small><strong id="fc-selected">0</strong></div><div class="fc-counter warn"><small>Ficando para trás</small><strong id="fc-left">0</strong></div></div>
                <div class="fc-delivery-scroll"><div class="fc-selection-state" id="fc-selection-state">Escolha projeto, destinatário e período para visualizar as distribuições.</div><table class="fc-delivery-table" id="fc-delivery-table" hidden><thead><tr><th style="width:42px">Incluir</th><th>Data</th><th>Cliente</th><th>Produto</th><th>Quantidade</th><th>Situação</th></tr></thead><tbody></tbody></table></div>
            </div>
            <input type="hidden" name="grouping_mode" id="fc-mode" value="customer">
            <div class="fc-actions"><button class="fc-btn" id="fc-close" type="button">Cancelar</button><button class="fc-btn fc-btn-primary" id="fc-submit" type="submit" disabled>Preparar folha selecionada</button></div>
        </div>
    </form>
    @endcan

    <div class="fc-table-wrap">
        @if($sheets->isEmpty())<div class="fc-empty"><i class="ph-duotone ph-clipboard-text" style="font-size:2rem"></i><p>Nenhuma folha foi criada ainda.</p></div>@else
        <table class="fc-table fc-desktop"><thead><tr><th></th><th>Folha</th><th>Destinatário</th><th>Período</th><th>Modo</th><th>Entregas</th><th>Situação</th><th>Ações</th></tr></thead><tbody>
        @foreach($sheets as $sheet)<tr>
            <td>@if($sheet->isApproved())<input type="checkbox" form="billing-form" name="sheet_ids[]" value="{{ $sheet->id }}" aria-label="Selecionar {{ $sheet->formatted_number }}">@endif</td>
            <td class="fc-number">{{ $sheet->formatted_number }} @if($sheet->revision>1)<small>r{{ $sheet->revision }}</small>@endif</td><td>{{ $sheet->recipient_name }}</td>
            <td>{{ $sheet->period_start->format('d/m/Y') }}–{{ $sheet->period_end->format('d/m/Y') }}</td><td>{{ $sheet->grouping_mode->label() }}</td><td>{{ $sheet->distributions_count }}</td>
            <td><span class="fc-badge">{{ $sheet->status->label() }}</span></td><td><a class="fc-link" href="{{ route('delivery.conference-sheets.show',[request()->route('tenant'),$sheet]) }}">Conferir</a></td>
        </tr>@endforeach</tbody></table>
        <div class="fc-mobile">@foreach($sheets as $sheet)<a class="fc-card" href="{{ route('delivery.conference-sheets.show',[request()->route('tenant'),$sheet]) }}"><span class="fc-card-head"><strong class="fc-number">{{ $sheet->formatted_number }}</strong><span class="fc-badge">{{ $sheet->status->label() }}</span></span><strong>{{ $sheet->recipient_name }}</strong><span class="fc-card-meta">{{ $sheet->period_start->format('d/m/Y') }}–{{ $sheet->period_end->format('d/m/Y') }} · {{ $sheet->distributions_count }} entregas</span></a>@endforeach</div>
        @can('prepare_billing_from_delivery_conference')<form id="billing-form" method="post" action="{{ route('delivery.conference-sheets.prepare-billing',request()->route('tenant')) }}" style="display:flex;justify-content:flex-end;padding:.7rem">@csrf<button class="fc-btn fc-btn-primary" type="submit">Preparar cobrança das selecionadas</button></form>@endcan
        @endif
    </div>
    {{ $sheets->links() }}
</div>
<script>
(()=>{const data=@json($projectData),oldRecipient=@json(old('recipient_id')),endpoint=@json(route('delivery.conference-sheets.eligible',request()->route('tenant'))),form=document.getElementById('fc-form'),project=document.getElementById('fc-project'),type=document.getElementById('fc-type'),recipient=document.getElementById('fc-recipient'),start=document.getElementById('fc-start'),end=document.getElementById('fc-end'),mode=document.getElementById('fc-mode'),table=document.getElementById('fc-delivery-table'),body=table.querySelector('tbody'),state=document.getElementById('fc-selection-state'),submit=document.getElementById('fc-submit');let timer=null,controller=null,items=[],restoreRecipient=oldRecipient;
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const counters=()=>{const available=items.filter(x=>x.available).length,selected=body.querySelectorAll('input:checked').length;document.getElementById('fc-total').textContent=items.length;document.getElementById('fc-available').textContent=available;document.getElementById('fc-selected').textContent=selected;document.getElementById('fc-left').textContent=Math.max(0,available-selected);submit.disabled=selected===0;};
const renderRows=()=>{body.innerHTML=items.map(x=>`<tr class="${x.available?'is-selected':'is-blocked'}"><td><input class="fc-check" type="checkbox" name="distribution_ids[]" value="${x.id}" ${x.available?'checked':'disabled'} aria-label="Incluir distribuição ${x.id}"></td><td>${esc(x.date)}</td><td>${esc(x.customer)}</td><td><strong>${esc(x.product)}</strong></td><td>${esc(x.quantity)} ${esc(x.unit)}</td><td>${x.available?'<span class="fc-badge">Disponível</span>':`Já está em ${esc(x.existing_sheet)}`}</td></tr>`).join('');table.hidden=false;state.hidden=true;body.querySelectorAll('input').forEach(input=>input.addEventListener('change',()=>{input.closest('tr').classList.toggle('is-selected',input.checked);counters();}));counters();};
const ready=()=>project.value&&recipient.value&&start.value&&end.value;
const load=async()=>{if(!ready()){items=[];table.hidden=true;state.hidden=false;state.className='fc-selection-state';state.textContent='Escolha projeto, destinatário e período para visualizar as distribuições.';counters();return;}controller?.abort();controller=new AbortController();state.hidden=false;table.hidden=true;state.className='fc-selection-state';state.textContent='Carregando distribuições aprovadas…';const params=new URLSearchParams({sales_project_id:project.value,recipient_type:type.value,recipient_id:recipient.value,period_start:start.value,period_end:end.value});try{const response=await fetch(`${endpoint}?${params}`,{headers:{Accept:'application/json'},signal:controller.signal});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.message||'Não foi possível carregar as distribuições.');items=payload.items||[];if(!items.length){table.hidden=true;state.hidden=false;state.className='fc-selection-state';state.textContent='Nenhuma distribuição aprovada foi encontrada neste filtro.';counters();return;}renderRows();}catch(error){if(error.name==='AbortError')return;items=[];table.hidden=true;state.hidden=false;state.className='fc-selection-state fc-selection-error';state.textContent=error.message;counters();}};
const schedule=()=>{clearTimeout(timer);timer=setTimeout(load,250);};const renderRecipients=()=>{const row=data[project.value]||{},list=type.value==='organization'?(row.organizations||[]):row.customers||[];recipient.innerHTML='<option value="">Selecione</option>'+list.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');recipient.disabled=!project.value;if(restoreRecipient&&list.some(x=>String(x.id)===String(restoreRecipient))){recipient.value=restoreRecipient;restoreRecipient=null;}mode.value=type.value==='organization'?'organization_detailed':'customer';schedule();};
project.addEventListener('change',renderRecipients);type.addEventListener('change',renderRecipients);recipient.addEventListener('change',schedule);start.addEventListener('change',schedule);end.addEventListener('change',schedule);document.getElementById('fc-reload').addEventListener('click',load);document.getElementById('fc-select-all').addEventListener('click',()=>{body.querySelectorAll('input:not(:disabled)').forEach(x=>{x.checked=true;x.closest('tr').classList.add('is-selected')});counters();});document.getElementById('fc-select-none').addEventListener('click',()=>{body.querySelectorAll('input:not(:disabled)').forEach(x=>{x.checked=false;x.closest('tr').classList.remove('is-selected')});counters();});document.getElementById('fc-new')?.addEventListener('click',()=>{form.classList.add('open');form.scrollIntoView({behavior:'smooth',block:'start'});});document.getElementById('fc-close')?.addEventListener('click',()=>form.classList.remove('open'));renderRecipients();})();
</script>
@endsection
