<style>
    .fin-shell{width: 100%;margin:0 auto;display:grid;gap:1rem;color:var(--color-text,#17201b)}
    .fin-head{display:flex;align-items:center;justify-content:space-between;gap:1rem;flex-wrap:wrap;padding:.9rem 1rem;border:1px solid var(--color-border,#dce5df);border-left:4px solid var(--color-primary,#16834a);border-radius:8px;background:var(--color-surface,#fff)}
    .fin-head h1{margin:0;font-size:1.2rem;letter-spacing:0;line-height:1.25}.fin-head p{margin:.2rem 0 0;color:var(--color-text-secondary,#607067);font-size:.82rem}
    .fin-actions{display:flex;gap:.5rem;align-items:center;flex-wrap:wrap}.fin-btn{min-height:40px;display:inline-flex;align-items:center;justify-content:center;gap:.42rem;padding:.58rem .78rem;border:1px solid var(--color-border,#d4ddd7);border-radius:7px;background:var(--color-surface,#fff);color:var(--color-text,#17201b);font-size:.8rem;font-weight:750;text-decoration:none;cursor:pointer}.fin-btn svg{width:17px;height:17px}.fin-btn-primary{border-color:var(--color-primary,#16834a);background:var(--color-primary,#16834a);color:#fff}.fin-btn-danger{border-color:#dc2626;color:#b91c1c;background:#fff}.fin-btn:disabled{opacity:.55;cursor:not-allowed}
    .fin-grid{display:grid;grid-template-columns:repeat(12,minmax(0,1fr));gap:.8rem}.fin-card{grid-column:span 12;min-width:0;padding:1rem;border:1px solid var(--color-border,#dce5df);border-radius:8px;background:var(--color-surface,#fff)}.fin-main{grid-column:span 7}.fin-side{grid-column:span 5}
    .fin-stat{grid-column:span 3}.fin-stat span{display:block;color:var(--color-text-secondary,#617067);font-size:.72rem;font-weight:700}.fin-stat strong{display:block;margin-top:.3rem;font-size:1.25rem;letter-spacing:0}.fin-stat small{display:block;margin-top:.15rem;color:var(--color-text-muted,#7d8982)}
    .fin-section-title{display:flex;align-items:center;justify-content:space-between;gap:.7rem;margin:0 0 .75rem}.fin-section-title h2{margin:0;font-size:.95rem;letter-spacing:0}.fin-section-title a{font-size:.76rem;color:var(--color-primary,#16834a);font-weight:750;text-decoration:none}
    .fin-tool-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:.6rem}.fin-tool{display:flex;align-items:center;gap:.7rem;min-width:0;padding:.72rem;border:1px solid var(--color-border,#dce5df);border-radius:7px;color:inherit;text-decoration:none}.fin-tool:hover{border-color:var(--color-primary,#16834a)}.fin-tool-icon{width:36px;height:36px;display:grid;place-items:center;flex:0 0 auto;border-radius:7px;background:var(--color-surface-soft,#f1f6f3);color:var(--color-primary,#16834a)}.fin-tool-icon svg{width:18px;height:18px}.fin-tool strong,.fin-tool span{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.fin-tool strong{font-size:.78rem}.fin-tool span{margin-top:.12rem;color:var(--color-text-muted,#78857d);font-size:.67rem}
    .fin-table-wrap{overflow:auto;border:1px solid var(--color-border,#dce5df);border-radius:7px}.fin-table{width:100%;border-collapse:collapse;font-size:.77rem}.fin-table th,.fin-table td{padding:.65rem .7rem;border-bottom:1px solid var(--color-border,#e2e8e4);text-align:left;vertical-align:middle;white-space:nowrap}.fin-table th{background:var(--color-surface-soft,#f7faf8);font-size:.67rem;color:var(--color-text-secondary,#607067)}.fin-table tr:last-child td{border-bottom:0}.fin-money{font-weight:800}.fin-income{color:#15803d}.fin-expense{color:#b91c1c}
    .fin-badge{display:inline-flex;align-items:center;padding:.2rem .45rem;border:1px solid #d5ddd8;border-radius:999px;font-size:.65rem;font-weight:750;background:#f8faf9}.fin-badge-issued{color:#166534;border-color:#bbd8c3;background:#f1f8f3}.fin-badge-cancelled{color:#991b1b;border-color:#e8c1c1;background:#fff7f7}
    .fin-filter{display:grid;grid-template-columns:minmax(180px,2fr) repeat(3,minmax(130px,1fr)) auto;gap:.55rem;align-items:end}.fin-field{display:grid;gap:.3rem;min-width:0}.fin-field label,.fin-label{font-size:.69rem;font-weight:750;color:var(--color-text-secondary,#607067)}.fin-input,.fin-select,.fin-textarea{width:100%;min-height:42px;padding:.58rem .65rem;border:1px solid var(--color-border-strong,#cbd6cf);border-radius:7px;background:var(--color-surface,#fff);color:var(--color-text,#17201b);font:inherit}.fin-textarea{min-height:76px;resize:vertical}.fin-input:focus,.fin-select:focus,.fin-textarea:focus{outline:2px solid color-mix(in srgb,var(--color-primary,#16834a) 22%,transparent);border-color:var(--color-primary,#16834a)}
    .fin-form-grid{display:grid;grid-template-columns:repeat(12,minmax(0,1fr));gap:.7rem}.fin-col-3{grid-column:span 3}.fin-col-4{grid-column:span 4}.fin-col-6{grid-column:span 6}.fin-col-8{grid-column:span 8}.fin-col-12{grid-column:span 12}.fin-error{color:#b91c1c;font-size:.68rem}.fin-alert{padding:.75rem .85rem;border:1px solid #c7ddd0;border-left:4px solid #16834a;border-radius:7px;background:#f5fbf7;font-size:.78rem}.fin-alert-error{border-color:#efc1c1;border-left-color:#dc2626;background:#fff7f7;color:#991b1b}
    .fin-item{display:grid;grid-template-columns:minmax(180px,4fr) minmax(90px,1fr) minmax(80px,1fr) minmax(120px,1.4fr) minmax(120px,1.4fr) 42px;gap:.5rem;align-items:end;padding:.7rem 0;border-bottom:1px solid var(--color-border,#e2e8e4)}.fin-item:last-child{border-bottom:0}.fin-item-total{min-height:42px;display:flex;align-items:center;font-weight:800;white-space:nowrap}.fin-icon-btn{width:40px;height:40px;display:grid;place-items:center;border:1px solid var(--color-border,#d5ddd8);border-radius:7px;background:#fff;color:#b91c1c;cursor:pointer}.fin-icon-btn svg{width:17px;height:17px}.fin-total{display:flex;justify-content:flex-end;align-items:baseline;gap:.7rem;padding-top:.8rem}.fin-total span{font-size:.76rem;color:var(--color-text-secondary,#607067)}.fin-total strong{font-size:1.35rem}
    .fin-detail-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:.7rem}.fin-detail{padding:.7rem;border:1px solid var(--color-border,#dce5df);border-radius:7px}.fin-detail span{display:block;font-size:.66rem;color:var(--color-text-secondary,#607067);font-weight:700}.fin-detail strong{display:block;margin-top:.2rem;font-size:.8rem;overflow-wrap:anywhere}
    .fin-empty{padding:1.5rem;text-align:center;color:var(--color-text-muted,#78857d);font-size:.8rem}.fin-pagination{margin-top:.8rem}.fin-danger-box{border-color:#e8c1c1;background:#fffafa}
    @media(max-width:900px){.fin-main,.fin-side{grid-column:span 12}.fin-stat{grid-column:span 6}.fin-tool-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.fin-filter{grid-template-columns:1fr 1fr}.fin-filter .fin-search{grid-column:1/-1}.fin-col-3,.fin-col-4{grid-column:span 6}.fin-item{grid-template-columns:2fr 1fr 1fr}.fin-item .fin-reference{grid-column:1/3}.fin-item-total{justify-content:flex-end}.fin-detail-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}
    @media(max-width:600px){.fin-shell{gap:.7rem}.fin-head{align-items:stretch}.fin-head .fin-actions{width:100%}.fin-head .fin-btn{flex:1}.fin-stat{grid-column:span 6;padding:.8rem}.fin-stat strong{font-size:1rem}.fin-tool-grid{grid-template-columns:1fr}.fin-filter{grid-template-columns:1fr}.fin-filter .fin-search{grid-column:auto}.fin-col-3,.fin-col-4,.fin-col-6,.fin-col-8{grid-column:span 12}.fin-item{grid-template-columns:1fr 1fr;padding:.8rem 0}.fin-item .fin-description,.fin-item .fin-reference{grid-column:1/-1}.fin-item-total{justify-content:flex-start}.fin-detail-grid{grid-template-columns:1fr}.fin-table th,.fin-table td{padding:.6rem}.fin-actions .fin-btn{flex:1}}
</style>
